const a = [
"PLEASE STAY","OF COURSE","TAKE EVERYTHING","STRAIGHT TO THE POINT","I SAID NO","I SAID YES","NOBODY ELSE",
"COME BACK","STAY HERE","DON'T MOVE","DON'T LOOK","DON'T ASK","DON'T CALL","DON'T LIE","DON'T WAIT",
"LET IT GO","HOLD ON","KEEP IT","KEEP QUIET","KEEP MOVING","KEEP DREAMING","KEEP IT SIMPLE",
"ONE MORE","NO MORE","NEVER AGAIN","ALWAYS LATE","ALWAYS HERE","MAYBE LATER","MAYBE NEVER",
"RIGHT NOW","NOT TODAY","NOT YET","ALMOST","STILL","ALREADY","AGAIN","AGAIN AND AGAIN",
"END","THE END","NO SIGNAL","NO NAME","NO FACE","NO LIGHT","NO SOUND","NO RULES","NO MERCY","NO FEAR",
"IN SILENCE","IN PRIVATE","IN PUBLIC","IN MOTION","IN LOOP","IN MUTE","IN MONO","IN STEREO",
"NOISE ONLY","SILENCE ONLY","JUST AIR","JUST WATER","JUST FIRE","JUST US","JUST ME","JUST YOU",
"PLEASE DON'T","PLEASE DO","PLEASE WAIT","PLEASE LEAVE","PLEASE LISTEN","PLEASE BREATHE","PLEASE REMEMBER",
"PLEASE FORGET","PLEASE RETURN","PLEASE STAY CLOSE","PLEASE STAY STILL","PLEASE STAY SAFE",
"TAKE IT EASY","TAKE YOUR TIME","TAKE ME HOME","TAKE ME BACK","TAKE THE NIGHT","TAKE THE KEY",
"TAKE THE FALL","TAKE THE RISK","TAKE THE LAST","TAKE THE FIRST","TAKE THE REST",
"MAKE IT REAL","MAKE IT FAST","MAKE IT SLOW","MAKE IT LOUD","MAKE IT QUIET","MAKE IT CLEAN","MAKE IT DIRTY",
"MAKE IT SIMPLE","MAKE IT WILD","MAKE IT TRUE","MAKE IT WRONG",
"TRUST ME","DON'T TRUST ME","FOLLOW ME","LEAVE ME","FIND ME","LOSE ME","SAVE ME","BREAK ME",
"TOO MUCH","NOT ENOUGH","SO CLOSE","SO FAR","SO EASY","SO HARD","SO SORRY","SO WHAT",
"WHAT NOW","WHY ME","WHY NOT","WHO CARES","WHO KNOWS","WHO ARE YOU","WHO AM I",
"ALL GOOD","ALL BAD","ALL NIGHT","ALL DAY","ALL ALONE","ALL TOGETHER","ALL AT ONCE",
"EVERYTHING CHANGES","NOTHING CHANGES","EVERYTHING ENDS","NOTHING ENDS",
"NO EXIT","NO ENTRY","NO RETURN","NO REFUND","NO CONTROL","NO CREDIT","NO FUTURE",
"LAST CALL","LAST NIGHT","LAST TIME","FIRST TIME","FINAL TAKE","FINAL CUT",
"THE RACE","THE CHASE","THE FALL","THE RISE","THE TIDE","THE TURN","THE SHIFT","THE GLITCH",
"ON REPEAT","ON PURPOSE","ON ACCIDENT","ON MY WAY","ON YOUR SIDE","ON THE EDGE","ON THE FLOOR",
"OFF LIMITS","OFF THE GRID","OFF THE RECORD","OFF THE MAP","OFF THE CLOCK",
"UNDER CONTROL","OUT OF CONTROL","UNDER WATER","UNDER FIRE","UNDER PRESSURE",
"OVER AND OVER","OVER THE LINE","OVER THE MOON","OVER THE CITY",
"BETWEEN US","BETWEEN LINES","BETWEEN WORLDS","BETWEEN NIGHTS","BETWEEN WAVES",
"WITHOUT YOU","WITHOUT ME","WITHOUT WORDS","WITHOUT SHAME","WITHOUT TIME",
"WITH YOU","WITH ME","WITH LOVE","WITH HATE","WITH CARE","WITH FEAR",
"FOR REAL","FOR GOOD","FOR NOTHING","FOR ONCE","FOR NOW",
"TOO LATE","TOO EARLY","TOO REAL","TOO QUIET","TOO LOUD","TOO CLEAN","TOO DIRTY",
"OKAY","NOT OKAY","I'M OK","I'M NOT","I REMEMBER","I FORGOT","I SWEAR","I PROMISE",
"I CAN'T","I WON'T","I WILL","I DID","I DO","I DON'T","I KNOW","I DON'T KNOW",
"KEEP YOUR EYES","KEEP YOUR WORD","KEEP YOUR HANDS","KEEP YOUR DISTANCE",
"TURN IT UP","TURN IT DOWN","TURN AROUND","TURN BACK","TURN OFF","TURN ON",
"PRESS PLAY","PRESS STOP","PRESS RECORD","PRESS RESET",
"NO FILTER","NO REVERB","NO DELAY","NO DRAMA","NO DOUBT","NO LOVE","NO HATE",
"PURE CHAOS","PURE CALM","PURE LUCK","PURE GOLD","PURE NOISE",
"NEVERMIND","MIND YOUR STEP","MIND YOUR BUSINESS","MIND THE GAP",
"TAKE A BREATH","LOSE YOURSELF","FIND YOURSELF","SAVE YOURSELF",
"THIS IS IT","THAT'S IT","THAT'S ALL","THAT'S LIFE","THAT'S LOVE",
"YOU KNOW","YOU DON'T","YOU DID","YOU DIDN'T","YOU WILL","YOU WON'T",
"CALL ME","DON'T CALL ME","TEXT ME","DON'T TEXT","MEET ME","DON'T MEET ME",
"WAIT FOR ME","DON'T WAIT","STAY WITH ME","LEAVE WITH ME",
"NO ANSWER","NO QUESTION","NO REASON","NO EXCUSES","NO APOLOGIES",
"YES PLEASE","NO THANKS","THANK YOU","SORRY","SORRY NOT SORRY",
"COME CLOSER","STEP BACK","SIT DOWN","STAND UP","WAKE UP","GO TO SLEEP",
"OPEN UP","SHUT UP","SHUT IT","OPEN THE DOOR","CLOSE THE DOOR",
"LOOK AT ME","LOOK AWAY","LOOK DOWN","LOOK UP","LOOK AGAIN",
"LISTEN","DON'T LISTEN","SPEAK","DON'T SPEAK","SAY IT","DON'T SAY IT",
"TOUCH ME","DON'T TOUCH","HOLD ME","LET ME GO",
"NO HEART","FULL HEART","COLD HEART","SOFT HEART",
"NO PLAN","NO HOME","NO PEACE","NO WAR","NO GODS","NO HEROES",
"ALL CAPS","NO CAPS","LOW KEY","HIGH KEY","MIDNIGHT","NOON",
"ZERO","ONE","TWO","THREE","FIVE","TEN","TWELVE","TWENTY FOUR","SIXTY",
"808","909","404","777","13","2000","1999","6676",
"TE MIRO","TE MIRO MIRANDO","NO ME MIRES","MÍRAME","MÍRAME BIEN","MÍRAME MAL",
"QUIEN ME VE","QUIEN TE VE","QUIEN NOS VE","NADIE ME VE","NADIE TE VE",
"POR FAVOR","SVP","S'IL TE PLAÎT","PER FAVORE","PLEASE",
"MENOS MAL","NI TAN MAL","QUE MÁS DA","NO PASA NADA","YA FUE","DA IGUAL",
"AQUÍ","AHORA","HOY","AYER","MAÑANA","NUNCA","SIEMPRE","JAMÁS","CASI",
"OTRA VEZ","UNA VEZ","DOS VECES","MIL VECES","POR ÚLTIMA VEZ",
"VEN","VEN AQUÍ","VEN CONMIGO","NO VENGAS","NO TE VAYAS","VETE",
"QUÉDATE","QUÉDATE AQUÍ","QUÉDATE CERCA","QUÉDATE LEJOS","NO TE QUEDES",
"SIGUE","SIGUE ASÍ","SIGUE RECTO","SIGUE SIN MÍ","SIGUE SIN TI",
"PARA","PARA YA","NO PARES","PÁRAME","NO TE PARES",
"SALTA","SALTANDO","NO SALTES","BAJA","SUBE","SUBE EL VOLUMEN","BAJA EL VOLUMEN",
"RESPIRA","NO RESPIRES","TRAGA","ESCUPE","SONRÍE","LLORA","RÍE","GRITA","SUSURRA",
"CALLA","NO CALLES","DILO","NO LO DIGAS","DÍMELO","NO ME LO DIGAS",
"LO SÉ","NO LO SÉ","NO SÉ NADA","SÉ DEMASIADO","LO SABES","NO LO SABES",
"NON SAPREI","NON LO SO","LO SO","IO E TE","IO E N","PERCHÉ","BASTA",
"DEMAIN MATIN","CE SOIR","TOUT DE SUITE","JE SAIS","JE NE SAIS PAS",
"EN SERIO","DE VERDAD","EN PAZ","EN GUERRA","EN CALMA","EN LLAMAS",
"EN SILENCIO","EN SECRETO","EN VOZ ALTA","EN BAJA","EN SOMBRA",
"CON CUIDADO","SIN CUIDADO","CON MIEDO","SIN MIEDO","CON FE","SIN FE",
"CON SUERTE","SIN SUERTE","CON RABIA","SIN RABIA","CON AMOR","SIN AMOR",
"SIN SEÑAL","SIN NOMBRE","SIN ROSTRO","SIN CUERPO","SIN TIEMPO","SIN MAPA",
"CON SEÑAL","CON NOMBRE","CON ROSTRO","CON CUERPO","CON TIEMPO",
"DEL BANCO","DE LA CALLE","DEL SUELO","DEL CIELO","DE NOCHE","DE DÍA",
"EN EL AIRE","BAJO EL AGUA","SOBRE EL FUEGO","DENTRO DE MÍ","FUERA DE MÍ",
"ENTRE DOS","ENTRE TRES","ENTRE LÍNEAS","ENTRE CAJAS","ENTRE SOMBRAS",
"POR DENTRO","POR FUERA","POR FIN","AL FIN","AL PRINCIPIO","AL FINAL",
"AL BORDE","AL CENTRO","AL VACÍO","AL RUIDO",
"TODO BIEN","TODO MAL","TODO LO MISMO","TODO CAMBIA","TODO ARDE","TODO PASA",
"NADA MÁS","NADA MENOS","NADA NUEVO","NADA REAL","NADA IMPORTA",
"ME VOY","ME QUEDO","ME PIERDO","ME ENCUENTRO","ME ROMPO","ME ARREGLAS",
"ME SALVAS","ME HUNDES","ME SIGUES","ME OLVIDAS","ME ACUERDO",
"TE VAS","TE QUEDAS","TE PIERDES","TE ENCUENTRAS","TE ROMPES",
"NO TE VAS","NO TE VAYAS","NO TE DUERMAS","NO TE RINDAS","NO TE ROMPAS",
"NO ME BUSQUES","NO ME SIGAS","NO ME LLAMES","NO ME NOMBRES",
"VUELVE","VUELVE YA","VUELVE A CASA","NO VUELVAS","VUELVE A EMPEZAR",
"EMPIEZA","EMPIEZA DE NUEVO","EMPIEZA AQUÍ","EMPIEZA AHORA",
"TERMINA","TERMINA BIEN","TERMINA MAL","TERMINA AQUÍ","TERMINA YA",
"EN LOOP","EN MUTE","EN MONO","EN ESTÉREO","EN CLIP","EN WARP",
"PLAY","STOP","REC","RESET","PAUSE",
"LUZ ROJA","LUZ VERDE","LUZ AZUL","NOCHE ROJA","DÍA NEGRO",
"SIN PRISA","CON PRISA","MUY LENTO","MUY RÁPIDO","A TIEMPO","FUERA DE TIEMPO",
"TODO DERECHO","TODO TORCIDO","TODO RECTO","TODO ROTO","TODO PEGADO",
"CONTRA TI","CONTRA MÍ","CONTRA TODO","A FAVOR","EN CONTRA",
"MI ÚLTIMA","TU ÚLTIMA","NUESTRA ÚLTIMA","MI PRIMERA","TU PRIMERA",
"NO HAY PLAN","NO HAY PAZ","NO HAY LUZ","NO HAY FINAL","NO HAY SEÑAL",
"HAY RUIDO","HAY LUZ","HAY FUEGO","HAY AGUA","HAY SOMBRA",
"YA SÉ","YA NO","AÚN NO","AÚN SÍ","CASI LISTO","NADA LISTO",
"CUÉNTAME","NO CUENTES","DIME","NO DIGAS","PREGUNTA","NO PREGUNTES",
"SI TE VAS","SI TE QUEDAS","SI ME MIRO","SI ME PIERDO","SI ME ENCUENTRAS",
"TE LO JURO","NO LO JURO","PALABRA","SIN PALABRAS",
"EN TU CARA","A TU ESPALDA","EN TU OÍDO","EN TU CUELLO","EN TU MANO",
"BAJO CERO","SOBRE CERO","EN CERO","EN MIL","EN INFINITO",
"NO HAY NADIE","HAY ALGUIEN","HAY NADIE","SOY NADIE","ERES NADIE",
"TODO POR NADA","NADA POR TODO","TODO POR TI","NADA SIN TI",
"ENTRA","SAL","ENTRA Y SAL","NO ENTRES","NO SALGAS",
"CIERRA","ABRE","CIERRA TODO","ABRE TODO","CIERRA LOS OJOS","ABRE LOS OJOS",
"SUBE","BAJA","SUBE MÁS","BAJA MÁS","SUBE UN POCO","BAJA UN POCO",
"CONTRÓLATE","NO TE CONTROLES","SÉ REAL","SÉ FALSO","SÉ SIMPLE","SÉ RARO",
"EN PAUSA","SIN PAUSA","SIN PARAR","HASTA AQUÍ","HASTA LUEGO",
"HASTA NUNCA","HASTA SIEMPRE","NOS VEMOS","NO NOS VEMOS",
"NO ME OLVIDES","OLVÍDAME","RECUÉRDAME","BÓRRAME","GUÁRDAME",
"TOCA","NO TOQUES","SUENA","NO SUENES","SUBE EL BPM","BAJA EL BPM",
"ENCIENDE","APAGA","APÁGAME","ENCIÉNDEME","APAGA TODO","ENCIENDE TODO"
];

const b = [
"veilness","afterform","versusness","migooid","boxless","bankvoid","forgottenism","cielbas","florcore",
"kneephase","lighterfall","magmaloop","fisherror","subdrift","ambientform","ravenmode","raceless",
"moondust","dancestate","neroblur","babycore","motherless","dovequiet","fearmass","monocode",
"barknoise","lookback","pointzero","silentfield","noisefloor","shadowplay","lightleak",
"smokestate","saltmemory","boxinside","wiretouch","glassmind","metalsoft","woodsignal",
"asphaltwarm","neonwet","cloudloss","skyshift","groundfeel","doorphase","windowdelay",
"hallform","cornerstatic","streetblur","bridgepulse","tunnelfade","metrosleep",
"shoreless","seasound","wavecut","stormhold","firelow","iceburn","ashtrace",
"dustsignal","tidalform","cometloss","planetdrift","satelliteghost","radioabsence",
"freqerror","signalfade","interferenza","heartbeatfake","pulsewrong","voiceless",
"echoafter","whispernoise","screamquiet","cryloop","laughcut","breakframe",
"glitchskin","loopmemory","sampleghost","takevoid","trackless","mixblur",
"masterfade","clipoff","warpinside","tempoless","bpmdrift","swingloss",
"grooveless","reverbinfinite","delayshort","chorusweak","distorsione",
"saturazione","filtermind","sidechainbreath","kickghost","snarefade","hathollow",
"bassweight","subpressure","eightzeroeight","ninezeronine","melodyloss",
"chordbroken","notawrong","scaleoff","keydrift","harmonicacheap",
"veil","versus","migoo","boxes","banco","olvidados","ciel","flor","knees","lighters","magma","fish","submarin",
"ambiente","raven","ravenow","race","moon","dance","nero","baby","mother","dove","miedos","mono","ladrido",
"mirada","punto","silencio","ruido","sombra","luz","humo","sal","caja","cables","cristal","metal","madera",
"asfalto","neón","nube","cielo","suelo","puerta","ventana","pasillo","esquina","calle","puente","túnel",
"metro","playa","mar","ola","tormenta","fuego","hielo","ceniza","polvo","marea","cometa","planeta",
"satélite","radio","frecuencia","señal","interferencia","latido","pulso","voz","eco","susurro","grito",
"llanto","risa","corte","error","glitch","loop","sample","toma","pista","mezcla","master","clip","warp",
"tempo","bpm","swing","groove","reverb","delay","chorus","distorsión","saturación","filtro","sidechain",
"kick","snare","hat","bass","sub","808","909","melodía","acorde","nota","escala","tonalidad","armónica",
"ruina","milagro","veneno","cura","karma","fiebre","fantasma","ángel","diablo","perro","gato","cuervo",
"paloma","sirena","lobo","mariposa","serpiente","hombre","mujer","niño","nadie","alguien","todos",
"ninguno","cuerpo","piel","hueso","sangre","corazón","mente","ojo","mano","cara","boca","lengua",
"espalda","pecho","vientre","cabeza","cuello","pierna","brazo","dedos","uñas","pulso","ritmo",
"tiempo","espacio","vacío","lleno","caos","orden","ruido blanco","ruido rosa","silencio negro",
"memoria","recuerdo","olvido","historia","cuento","mensaje","nota vocal","archivo","carpeta","backup",
"papel","foto","imagen","sombra larga","luz fría","luz roja","luz azul","luz negra","reflejo",
"espejo","vidrio","pantalla","pixel","resolución","frame","corte seco","fundido","blur","grano",
"textura","patrón","forma","línea","punto y coma","paréntesis","comillas","asterisco",
"archivo roto","sistema","proceso","buffer","latencia","driver","interfaz","cable usb","corriente",
"batería","voltaje","carga","descarga","chispa","motor","rueda","velocidad","freno","choque",
"deriva","trayectoria","caída","impacto","fractura","fisura","cicatriz","herida","costura",
"remiendo","pegamento","cinta","alambre","clavo","martillo","herrumbre","óxido","polilla",
"moho","arena","barro","tierra","cemento","polvo fino","grava","piedra","roca","lava",
"cráter","volcán","isla","continente","frontera","límite","borde","centro","núcleo",
"zona","área","sector","barrio","bloque","torre","edificio","azotea","sótano","garaje",
"puerto","muelle","barco","bote","ancla","vela","corriente","deriva","naufragio",
"avión","ala","turbina","cabina","pista","aterrizaje","despegue","trayecto",
"maleta","equipaje","objeto","cosa","resto","residuo","sobras","fragmento","pieza",
"parte","mitad","doble","triple","copia","original","falsificación","eco largo",
"delay corto","reverb infinita","silencio roto","ruido crudo","voz sola","voz múltiple",
"coro","unísono","armonía","disonancia","tensión","resolución","cadencia","final",
"intro","outro","puente","drop","build","break","fill","loop infinito",
"noche","día","madrugada","tarde","amanecer","atardecer","crepúsculo",
"invierno","verano","otoño","primavera","clima","niebla","lluvia","granizo",
"viento","calor","frío seco","frío húmedo","fuego lento","humo denso",
"perfume","olor","sudor","saliva","aliento","eco humano","presencia",
"ausencia","distancia","cercanía","contacto","choque frontal",
"amor","odio","duda","miedo","fe","culpa","deseo","impulso","instinto",
"rutina","gesto","tic","manía","costumbre","obsesión","ritual",
"secreto","mentira","verdad","promesa","amenaza","silencio incómodo",
"palabra","frase","sílabas","sonido gutural","ruido mecánico",
"idioma","lengua muerta","acento","error gramatical","traducción",
"francés roto","inglés mal","italiano crudo","español torcido",
"numero","código","cifra","clave","pin","password","secuencia",
"patrón extraño","orden oculto","azar","random","ruleta","suerte",
"fracaso","intento","ensayo","error humano","fallo técnico",
"máquina","algoritmo","script","línea","variable","constante",
"bucle","condición","salida","entrada","input","output",
"pantano","bosque","árbol","raíz","rama","hoja","semilla",
"fruto","cáscara","pulpa","hueso duro","espina","aguijón",
"animal nocturno","animal urbano","animal herido","animal suelto",
"cuarto","habitación","cama","sábanas","almohada","pared",
"techo","suelo frío","mancha","marca","huella","pisada",
"camino","sendero","ruta","atajo","desvío","error de ruta",
"mapa","brújula","norte","sur","este","oeste","coordenada",
"kilómetro","metro","centímetro","milímetro","segundo",
"minuto","hora","día cero","año perdido","fecha falsa",
"archivo final","versión beta","demo","borrador","preview",
"release","silencio final",
"ruinstate","miraclefake","poisonsoft","curefalse","karmaloop","feverlow",
"phantomtouch","angelnoise","devilcalm","dogmemory","catstatic","crowwatch",
"doveshadow","sirensleep","wolfinside","butterflycut","snakecoil",
"someoneelse","noonehere","anybody","everybodyelse","nobodyleft",
"bodyecho","skinfile","bonewhite","bloodwarm","heartbuffer","mindcache",
"eyecontactless","handdelay","faceblur","mouthquiet","tongueless",
"backweight","chestpressure","gutfeeling","headnoise","necktension",
"limbless","fingertrace","nailmark","pulseflat","rhythmwrong",
"timefold","spaceleak","voidfill","fullvoid","chaossoft","orderfake",
"whitewhitenoise","pinknoise","blackquiet","memoryleak","recallerror",
"forgetmode","storyless","messagelost","voicenoteempty","archivodead",
"folderghost","backupfailed","paperthin","photoblur","imageburn",
"shadowlong","coldlight","redlightdelay","bluelightsoft","blacklightfake",
"reflectionoff","mirrorwrong","glassscreen","pixelhurt","resolutionlow",
"framecut","hardcut","softfade","motionblur","grainfeel",
"texturedoubt","patternbroken","formless","linewrong","semicolonlife",
"parenthesisopen","quotationempty","asterisklost",
"corruptedfile","systemdrift","processidle","bufferunderrun",
"latencyinside","driverghost","interfacecold","usbnoise",
"powerdrop","batteryweak","voltagelow","chargecycle","dischargecurve",
"sparkquiet","enginebreath","wheelspin","speedless","brakehold",
"impactsoft","fractalline","crackstate","scarlogic","woundopen",
"stitchmemory","patchwork","tapedown","wiredwrong","rusted",
"oxidation","mothdust","moldgreen","sandmemory","mudslow",
"earthtone","cementcold","finepowder","gravelvoice","stonemute",
"rockpressure","lavaflow","craterinside","volcanosleep",
"isolation","borderless","limitstate","edgefeel","centerloss",
"zoneblur","areavoid","sectorfade","blockform","toweralone",
"rooftopnight","basementecho","garagecold",
"harborless","dockquiet","boatdrift","anchorlost","sailfold",
"currentwrong","derivemode","shipwreckinside",
"wingless","turbinenoise","cabindim","runwayghost","landinglate",
"takeoffearly","patherror",
"luggageempty","objectless","thingness","leftovers","residuefeel",
"fragmented","piecewise","partial","halfstate","doublethink",
"tripleghost","copyloss","originalfake","longecho",
"shortdelay","endlessreverb","brokenquiet","rawnoise",
"lonelyvoice","multivoice","chorusnone","unisonoff",
"harmonyweak","dissonant","tensionhold","resolutionmiss",
"cadenceless","finalform",
"introvoid","outrofade","bridgeghost","dropmissed","buildsoft",
"breakslow","fillempty","infiniteloop",
"nightstate","dayblur","lateness","earlywrong","sunrisefake",
"sunsetdelay","twilightzone",
"seasonless","weatherinside","fogmemory","rainpattern","hailnoise",
"windcut","heatghost","coldpressure","slowfire","densehaze",
"scenttrace","odorless","sweatsalt","breathwarm","humanecho",
"presencefelt","absenceheavy","distanceweight","nearnessfear",
"contacterror","frontalimpact",
"loveghost","hatequiet","doubthold","fearsoft","faithweak",
"guiltloop","desirelow","impulsecut","instinctmute",
"routineblur","gesturelost","ticnoise","habitform","obsessionsoft",
"ritualempty",
"secretopen","lietrace","truthfake","promisebroken","threathold",
"awkwardsilence",
"wordless","phrasecut","syllablewrong","gutturalsound",
"mechanicalnoise",
"deadlanguage","accentwrong","brokenfrench","badenglish",
"roughitaliano","twistedespañol",
"numberless","codecold","digitghost","keylost","pinwrong",
"passwordvoid","sequencerandom",
"hiddenorder","purechance","roulettefeel","lucklow",
"failstate","attemptloop","trialerror","humanfault",
"technicalfault",
"machinefeel","algorithmsoft","scriptless","linenoise",
"variableghost","constantfake","loopinside","conditionfalse",
"exitmissing","inputvoid","outputnoise"
];

const c = [
"versus","vs","into","in","inside","within","without","between","among","against","towards","away from",
"before","after","during","while","when","where","until","since","through","across","around","behind",
"beneath","below","above","over","under","beyond","past","near","far from",
"//","///","…","—","--","::",":::","___","++","+=",
"≈","≠","<",">","≤","≥","∞","∅","∴","∵",
"&","&&","||","!?","?!","!!","??","..",".",
"between","unbetween","inbetween","outbetween","misbetween",
"pre","post","anti","proto","meta","ultra","infra","pseudo",
"non-","re-","de-","un-","dis-","over-","under-","counter-",
"as","as_as","as-if","as-not","as//error",
"like","unlike","like_this","not_like_this",
"from","from/from","from nowhere","from inside","from error",
"to","to/to","to nowhere","to inside","to error",
"of","of/of","of nothing","of noise","of loss",
"with","with/with","without/with","with error","with delay",
"without","without/without","without meaning","without exit",
"via","via/via","via noise","via silence",
"per","per/per","per errore","per sbaglio","per niente",
"de","de/de","de nada","de nadie","de error",
"del","del/del","del ruido","del fallo",
"entre","entre/entre","entre nadie","entre todo",
"tra","tra/tra","tra niente","tra tutto","tra errori",
"fra","fra/fra","fra zero","fra mille",
"con","con/con","con miedo","con error","con nada",
"sin","sin/sin","sin nadie","sin forma","sin razón",
"sobre","sobre/sobre","sobre nada","sobre ruido",
"bajo","bajo/bajo","bajo cero","bajo nadie",
"tras","tras/tras","tras error","tras ruido",
"hacia","hacia/hacia","hacia nadie","hacia dentro",
"verso","verso/verso","verso il nulla","verso errore",
"against","against/against","against sense","against form",
"contro","contro/contro","contro tutto","contro niente",
"before","before/after","before nothing","before error",
"after","after/after","after silence","after loss",
"during","during/during","during nothing","during glitch",
"while","while/while","while breaking","while fading",
"cuando","cuando/cuando","cuando nadie","cuando nada",
"mentre","mentre/mentre","mentre cade","mentre sbaglia",
"dove","dove/dove","dove nessuno","dove niente",
"where","where/where","where lost","where wrong",
"if","if/if","if error","if never","if still",
"else","else/else","elsewhere","else error",
"unless","unless/unless","unless broken",
"maybe","maybe/maybe","maybe not","maybe error",
"perhaps","perhaps/perhaps","perhaps wrong",
"como","como/como","como ruido","como nada",
"come","come/come","come errore","come segnale",
"as noise","as silence","as glitch","as absence",
"between//","between??","between…","between void",
"entre//","entre???","entre error","entre nadie",
"tra///","tra…","tra vuoto","tra errore",
"before//after","after//before","now//then","here//gone",
"a","a/a","a nadie","a nada","a dentro",
"al","al/al","al borde","al fallo","al ruido",
"nel","nel/nel","nel mezzo","nel vuoto",
"en","en/en","en nada","en nadie","en error",
"inside","inside/inside","inside wrong","inside noise",
"outside","outside/outside","outside sense",
"above","above/above","above nothing",
"below","below/below","below zero",
"over","over/over","over error","over time",
"under","under/under","under skin","under noise",
"off","off/off","off sense","off grid",
"on","on/on","on error","on repeat",
"loop","loop/loop","looping","looped",
"repeat","repeat/repeat","repeat until",
"pause","pause/pause","paused",
"mute","mute/mute","muted",
"skip","skip/skip","skipping",
"cut","cut/cut","hardcut","softcut",
"fade","fade/fade","fadein","fadeout",
"break","break/break","breakpoint",
"drop","drop/drop","dropped",
"build","build/build","building",
"fail","fail/fail","failed",
"error","error/error","errorless",
"null","null/null","nullified",
"void","void/void","voided",
"random","random/random","randomized",
"noise","noise/noise","noisy",
"silence","silence/silence","silenced",
"glitch","glitch/glitch","glitched",
"buffer","buffer/buffer","buffering",
"latency","latency/latency","lagging",
"desync","desync/desync","outofsync",
"∞/0","0/∞","?/∞","?/0",
"before_end","after_end","no_end",
"start/end","end/start","end//end",
"here","here/here","here nowhere",
"there","there/there","there gone",
"now","now/now","now never",
"then","then/then","then lost",
"always","always/never","never/always",
"never","never/never","never again",
"again","again/again","again wrong",
"once","once/once","once broken",
"twice","twice/twice","twice wrong",
"many","many/many","many times",
"none","none/none","none left",
"all","all/all","all gone",
"half","half/half","half wrong",
"double","double/double","double back",
"triple","triple/triple","triple error",
"asleep","awake/asleep","halfawake",
"alive","alive/dead","dead/alive",
"up","up/down","down/up",
"left","left/right","right/left",
"forward","forward/back","back/forward",
"inside/out","out/inside",
"yes/no","no/yes","maybe/not",
"if yes","if no","if wrong",
"until","until/until","until nothing",
"finché","finché/non","finché rotto",
"hasta","hasta/hasta","hasta nadie",
"quando","quando/non","quando finisce",
"nowhere","nowhere/nowhere","nowhere near",
"somewhere","somewhere/somewhere","somewhere else",
"everywhere","everywhere/nowhere",
"anywhere","anywhere/else",
"between now","between never","between error",
"and","or","but","yet","so","nor","although","because","if","else","unless","as if","as though",
"of","from","to","for","with","without","by","via","per","plus","minus",
"de","del","de la","de los","de las","desde","hasta","entre","contra","hacia",
"con","sin","sobre","bajo","tras","antes de","después de","durante",
"y","o","pero","aunque","mientras","cuando","donde","como si","tal vez",
"da","do","nel","nella","nei","nelle","tra","fra","contro","verso",
"con te","senza te","dentro","fuori","prima di","dopo","durante",
"e","o","ma","anche se","mentre","quando","dove","come se",
"entre deux","sans","avec","contre","vers","avant","après","pendant",
"et","ou","mais","alors","comme si","peut-être",
"along","alongside","amid","amidst","circa","despite","except","including",
"excluding","following","preceding","regarding","concerning","according to",
"as","like","unlike","than","rather than","instead of","in place of",
"inside of","outside of","on top of","at the edge of","in the middle of",
"al borde de","en medio de","a través de","al lado de","encima de","debajo de",
"fuera de","dentro de","cerca de","lejos de","junto a","separado de",
"nel mezzo","ai margini","al centro di","lontano da","vicino a",
"au milieu de","au bord de","loin de","près de",
"throughout","all over","all along","right before","right after",
"just before","just after","almost","barely","nearly","hardly",
"maybe","perhaps","possibly","probably","definitely not",
"como","como si fuera","como nunca","como siempre","como nadie",
"perché","porque","parce que","because of","due to","thanks to",
"owing to","in spite of","despite of","regardless of",
"según","segundo","secondo","selon","according",
"if not","if ever","if only","even if","even when","even though",
"unless and until","so that","in order to","para que","pour que",
"between the lines","between breaths","between seconds","between errors",
"entre latidos","entre sombras","entre líneas","entre ruidos",
"tra errori","tra battiti","tra sogni",
"before sleep","after noise","during silence","while fading",
"antes del fin","después del eco","durante el fallo",
"prima del buio","dopo il rumore",
"in loop","on repeat","on pause","on mute","in mono","in stereo",
"en loop","en pausa","en mute","en mono","en estéreo",
"nel loop","in pausa","in muto",
"off","on","offline","online","out of sync","in sync",
"fuera de fase","fuera de tiempo","a tiempo",
"senza tempo","fuori tempo",
"as long as","as soon as","as far as","as much as",
"hasta que","tan pronto como","en cuanto",
"finché","non appena",
"around midnight","before dawn","after dusk","at noon",
"antes de ayer","después de mañana","hoy mismo",
"nel frattempo","mientras tanto","entre tanto",
"in between","somewhere between","nowhere near",
"más allá de","más acá de","menos que","más que",
"più di","meno di",
"au-delà de","en-deçà de",
"against the grain","with the flow","out of place","in place",
"fuera de lugar","en su sitio",
"as noise","as silence","as error","as memory",
"como ruido","como silencio","como fallo","como recuerdo",
"come errore","come memoria",
"toward nothing","from nowhere","into nowhere",
"hacia nadie","desde ningún lado",
"da nessuna parte","verso il nulla",
"side by side","face to face","back to back",
"cara a cara","espalda con espalda",
"faccia a faccia",
"one after another","over and over","again and again",
"una y otra vez","otra vez más",
"ancora e ancora",
"through error","through love","through fear",
"a través del error","a través del miedo",
"attraverso l’errore",
"under pressure","under water","under skin",
"bajo presión","bajo el agua","bajo la piel",
"sotto pressione","sotto pelle",
"over time","over distance","over noise",
"sobre el tiempo","sobre la distancia",
"sopra il rumore",
"between now and never","between here and gone",
"entre ahora y nunca","entre aquí y nadie",
"tra ora e mai",
"as a mistake","as a signal","as a warning",
"como un error","como señal","como aviso",
"come segnale",
"until it fades","until it breaks","until it ends",
"hasta que se apague","hasta que falle",
"finché finisce"
];

const d = [
"////","/////","//////","???","¿¿¿","!!!","…","……","—","–––","___","___core",
"non-non","antianti","postpost","metameta","ultraanti","protoerror","pseudonull",
"almostalmost","nevernever","alwaysnever","nowhereish","somewhen","anytimewrong",
"prebirth","postdeath","midvoid","afterafter","beforebefore",
"dead-on-arrival","alive-too-late","born-wrong","unfinished-again",
"softfail","hardmaybe","almost-broken","barely-alive","nearly-gone",
"unfeelable","overfelt","underfelt","misfelt","feltwrong",
"timeless-ish","timeleak","timebleed","clockless","desynced-forever",
"ghosted","halfghost","doubleghost","ghost-adjacent","almost-present",
"nullified","voided-out","emptied-full","full-of-nothing","nothing-heavy",
"overexposed","underexposed","misexposed","blind-lit","dark-lit",
"unsounded","oversounded","undersounded","noise-sick","silence-sick",
"memorycorrupt","memoryloop","memoryhole","memoryless+","rememberingless",
"futureless","past-heavy","present-missing","now-error",
"human-ish","almost-human","posthuman","prehuman","inhuman-lite",
"machine-soft","machine-wrong","machine-tired","algorithm-sad",
"cold-warm","warm-cold","hot-freeze","slow-fast","fast-stuck",
"bent-straight","crooked-clean","clean-dirty","dirty-pure",
"fake-true","true-false","real-ish","hyperreal","subreal",
"overloved","underloved","love-null","hate-flat","emotion-error",
"fear-muted","panic-low","anxiety-static","calm-broken",
"faithless+","belief-glitch","hopebuffer","hopeless-lite",
"desireless","desire-noise","want-error","need-undefined",
"zeroed","negative-one","fractional","irrational","imaginary",
"π-ish","e^error","√nothing","NaN","undefined",
"beta-broken","alpha-failed","release-never","final-never-final",
"v0.0.0","v∞","v?.?","patch-missing","rollbacked",
"mono-stuck","stereo-collapse","wide-narrow","panicked-left",
"rightless","center-lost","side-heavy",
"dry-wet","wet-dry","send-only","return-missing","bus-error",
"clipped-soft","unclipped-hard","distortion-clean","clean-distortion",
"reverbless","delayless","feedback-low","feedback-infinite",
"loop-fatigue","loop-sickness","loop-addiction","loop-burnout",
"grain-overdose","bitcrushed-soft","hires-noise","lofi-too-clean",
"signal-anxious","signal-tired","signal-lost","signal-lying",
"offline-only","online-nowhere","ghost-mode+","airplane-forever",
"sleep-deprived","dream-corrupt","awake-wrong","half-dreaming",
"drunk-on-silence","sober-on-noise","lucid-ish","blur-aware",
"too-early-again","too-late-again","never-on-time","always-off",
"pre-apology","post-regret","mid-mistake","error-in-progress",
"unfinished///","done??","complete-ish","almost-final",
"private-public","public-secret","secret-open","open-hidden",
"locked-open","open-locked","keyless","password-forgotten",
"screen-burned","screen-blank","screen-watching-you",
"seen-by-none","heard-by-error","felt-by-nobody",
"touchless","over-touched","untouchable-ish",
"language-broken","grammar-missing","syntax-error",
"meaning-overflow","meaning-null","meaning-pending",
"english-ish","español-raro","italiano-torcido","français-faux",
"spoken-wrong","said-too-much","unsaid-everything",
"capitalized-wrong","lowercased-too-hard","mixedCase-panic",
"punctuation-lost","comma-sick","period-missing",
"hashtagless","slash-heavy","backslash-life",
"left-behind","right-wrong","upside-failed","downside-only",
"forwardless","backward-only","stuck-midway",
"here-but-not","there-but-never","now-but-gone",
"present-but-absent","absent-too-present",
"alone-togetherish","together-alone","crowded-empty",
"nobody-everyone","someone-noone","anyone-none",
"fragile++","solid--","liquid-ish","gaslighted",
"burned-cold","frozen-hot","ash-wet","smoke-dense",
"cheap-feeling","priceless-error","free-but-costly",
"owned-by-none","borrowed-forever","returned-never",
"clean-failure","beautiful-mistake","ugly-perfect",
"wrong-but-right","right-but-empty",
"calculated-wrong","random-controlled","chaos-managed",
"order-faked","pattern-hallucinated",
"minimal-overload","maximal-silence",
"small-too-big","huge-too-small",
"edge-only","center-missing","borderline-everything",
"almost-art","almost-music","almost-nothing",
"this-isnt-it","this-is-it??","maybe-this",
"don’t-name-this","unnamable","name-error",
"no-title","title-pending","title-corrupt",
"endless-end","ending-start","startless",
"finished-unfinished","over-but-on",
"still-not-still","moving-nowhere","stopped-in-motion",
"alive-error","dead-buffering","life-lag",
"existence-lite","being-optional","optional-self",
"self-missing","self-too-much","self-noise",
"ego-muted","identity-glitch","persona-broken",
"mask-on-mask","face-off-face","mirror-wrong",
"seen-too-close","seen-too-far","focus-missed",
"clarity-overdose","blur-addicted",
"nothing-special","special-nothing",
"this-again","not-this","never-this",
"last-again","first-again","again-again",
"stolen","forgotten","unseen","unheard","unsaid","untitled","unnamed","unmade","unwritten","unborn",
"broken","bent","blurred","burned","faded","glitched","warped","muted","paused","looped",
"raw","cold","warm","wet","dry","dark","bright","soft","hard","thin","heavy",
"empty","full","hollow","dense","flat","deep","shallow","still","moving","drifting",
"quiet","loud","silent","noisy","clean","dirty","pure","impure","real","fake",
"true-ish","almost","barely","nearly","still","already","again","forever","never",
"late","early","wrong-time","off-time","in-time","out-of-sync","in-phase","off-phase",
"lowkey","highkey","midnight","noonish","dawnlike","dusklike","night-only","day-only",
"mono","stereo","wide","narrow","centered","sideways","upside-down","backwards","inside-out",
"red","blue","black","white","grey","violet","neon","nero","bianco","rosso","blu",
"verde","gris","oscuro","claro","roto","entero","torcido","recto","raro","normal",
"sereno","tenso","calmo","furioso","lento","rápido","piano","forte","sottile","pesante",
"miedo","miedos","fe","culpa","deseo","hambre","sed","fiebre","vértigo","ansia",
"amor","odio","duda","nada","todo","nadie","alguien","casi-nadie","casi-todo",
"svuoto","vuoto","pieno","niente","tutto","nessuno","qualcuno","forse","mai","sempre",
"demain","matin","ce soir","notte","giorno","oggi","ieri","mañana","hoy","ayer",
"de repente","sin razón","por dentro","por fuera","a escondidas","a plena luz",
"sin señal","sin nombre","sin cara","sin cuerpo","sin tiempo","sin mapa","sin vuelta",
"con señal","con nombre","con cara","con cuerpo","con tiempo","con duda","con ruido",
"of course","menos mal","svp","per favore","por favor","please","grazie","merci",
"tipo","modo","vibe","mood","aesthetic","core","anti-core","post-core","meta-core",
"hyper","ultra","infra","inter","extra","proto","pseudo","anti","post","pre",
"meta","non","re","de","un","dis","over","under","counter","contra","versus",
"null","void","zero","one","two","three","five","ten","twelve","twentyfour","sixty",
"808","909","404","777","13","2000","1999","6676","0000","0001","0101","1111",
"v1","v2","v3","beta","alpha","demo","draft","final","final_final","final2",
"low","mid","high","sub","wideband","narrowband","bandlimited","clipped","unclipped",
"distorted","saturated","overdriven","underdriven","filtered","unfiltered","sidechained",
"reverbed","delayed","dry","wet","pre","post","send","return","bus","mastered",
"glitchy","grainy","crispy","muddy","hazy","shimmery","cracked","stuttered","chopped",
"drunk","sober","awake","asleep","halfawake","halfdead","alive-ish","dead-ish",
"good","bad","okay","not-okay","fine","not-fine","so-so","too-much","not-enough",
"mi","tu","su","our","your","my","solo","together","alone","alone-together",
"first","last","only","second","third","next","previous","old","new","new-old",
"ancora","ancora","otra vez","otra","again","again","ancora una volta","otra más",
"mal","bien","mejor","peor","igual","diferente","same","different","similar",
"subtle","obvious","hidden","open","closed","locked","unlocked","blocked","unblocked",
"private","public","secret","secreto","segreto","oculto","visible","invisible",
"fragile","solid","liquid","gas","smoke","ash","dust","sand","salt","sugar",
"cheap","expensive","free","priceless","stolen","borrowed","lent","returned","lost","found",
"blue-screen","black-screen","white-screen","no-screen","screenless",
"online","offline","airplane-mode","ghost-mode","silent-mode",
"error-prone","errorless","faulty","stable","unstable",
"random","deterministic","chaotic","orderly","patterned","patternless",
"minimal","maximal","micro","macro","mini","mega",
"italiano","spagnolo","english","français","broken-english","italiano rotto","español torcido",
"sin sentido","no-sense","sense-less","meaningless","meaningful-ish",
"corto","largo","breve","infinito","finite","endless","end-ish",
"punto.","coma,","dos_puntos:","paréntesis()","corchetes[]","llaves{}",
"uppercase","lowercase","MiXeD","CAPSLOCK","whispercase",
"straight","crooked","side","diagonal","parallel","perpendicular",
"clean-cut","rough-cut","hard-edge","soft-edge",
"warm-light","cold-light","low-light","black-light","red-light","blue-light",
"slowburn","fastfall","softcrash","hardlanding",
"near","far","close","distant","cerca","lejos","vicino","lontano",
"inside","outside","dentro","fuori","dentro-fuori","fuori-dentro",
"here","there","now","then","aquí","allí","ora","poi",
"before","after","prima","dopo","antes","después"
];

function randChoice(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateTitle(aList, bList, cList, dList) {
  const A = randChoice(aList);
  const B = randChoice(bList);
  const C = randChoice(cList);
  const D = randChoice(dList);

  const plantillas = ["minimal", "rare", "abstract", "glitch"];
  const plantilla = randChoice(plantillas);

  let opciones = [];
  if (plantilla === "minimal") {
    opciones = [A, B, C, `${B} ${D}`];
  } else if (plantilla === "rare") {
    opciones = [`${A} ${B}`, `${B} ${C}`, `${A} ${C} ${B}`];
  } else if (plantilla === "abstract") {
    opciones = [`${B} ${C} ${D}`, `${C} ${B} ${D}`, `${D} ${B}`];
  } else {
    opciones = [`${B} ${D} ${B}`, D, `${C} ${B}`];
  }

  return randChoice(opciones);
}

function generateAlbum(nTracks) {
  const albumTitle = generateTitle(a, b, c, d);
  const lines = [];
  lines.push("Album:");
  lines.push(albumTitle);
  lines.push("");
  lines.push("Tracks:");
  for (let i = 1; i <= nTracks; i++) {
    lines.push(`${i}. ${generateTitle(a, b, c, d)}`);
  }
  return lines.join("\n");
}

const tracksInput = document.getElementById("tracks");
const out = document.getElementById("out");
const genBtn = document.getElementById("gen");
const shareBtn = document.getElementById("share");

function render() {
  const n = Math.max(1, Math.min(50, parseInt(tracksInput.value || "1", 10)));
  const text = generateAlbum(n);
  out.textContent = text;
  return text;
}

genBtn.addEventListener("click", render);

shareBtn.addEventListener("click", async () => {
  const text = out.textContent.trim() === "Pulsa el botón…" ? render() : out.textContent;

  if (navigator.share) {
    try {
      await navigator.share({ title: "Track Names Generator", text });
      return;
    } catch (_) {}
  }

  try {
    await navigator.clipboard.writeText(text);
    out.textContent = text + "\n\n[COPIADO ✅]";
  } catch (e) {
    alert("No se pudo copiar. Selecciona el texto y cópialo manualmente.");
  }
});

